services:
  sda:
    build:
      context: .
      dockerfile: apps/sda/Dockerfile
      args:
        - BUILDPLATFORM
        - TARGETPLATFORM
        - ENVIRONMENT=${ENVIRONMENT:-testnet}
    image: ${IMAGE_NAME}
    platform: ${BUILDPLATFORM}