services:
  sda:
    build:
      context: .
      dockerfile: apps/sda/Dockerfile
      args:
        - BUILD_PLATFORM
        - TARGETPLATFORM
    image: ${IMAGE_NAME}
    platform: ${BUILD_PLATFORM}