/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Timestamp } from "./common";
import { RoyaltyInfoResponse } from "./Sg721Base";

export type Uint128 = string;
export interface InstantiateMsg {
  admin?: string | null;
  admin_fee: number;
  cw721_code_id: number;
  max_bundles?: number | null;
  max_infusions?: number | null;
  max_per_bundle?: number | null;
  min_creation_fee?: Coin | null;
  min_infusion_fee?: Coin | null;
  min_per_bundle?: number | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  update_config: {};
} | {
  create_infusion: {
    infusions: Infusion[];
  };
} | {
  infuse: {
    bundle: Bundle[];
    infusion_id: number;
  };
};
export type Addr = string;
export interface Infusion {
  owner: string;
  description: string | null;
  collections: NFTCollection[];
  infused_collection: InfusedCollection;
  infusion_params: InfusionParams;
  payment_recipient?: Addr | null;
}
export interface NFTCollection {
  addr: Addr;
  min_req: number;
  max_req?: number | null;
  payment_substitute?: Coin | null;
}
export interface InfusedCollection {
  addr?: string | null;
  admin?: string | null;
  name: string;
  description: string;
  base_uri: string;
  image: string;
  num_tokens: number;
  sg: boolean;
  symbol: string;
  royalty_info?: RoyaltyInfoResponse | null;
  start_trading_time?: Timestamp | null;
  explicit_content?: boolean | null;
  external_link?: string | null;
}
export interface InfusionParams {
  mint_fee?: Coin | null;
  params?: BurnParams | null;
}
export interface BurnParams {
  compatible_traits?: CompatibleTraits | null;
}
export interface CompatibleTraits {
  a: string;
  b: string;
}
export interface Bundle {
  nfts: NFT[];
}
export interface NFT {
  addr: Addr;
  token_id: number;
}
export type QueryMsg = {
  config: {};
} | {
  infusion: {
    addr: Addr;
    id: number;
  };
} | {
  infusion_by_id: {
    id: number;
  };
} | {
  infusions: {
    addr: Addr;
    index: number;
  };
} | {
  is_in_bundle: {
    collection_addr: Addr;
    infusion_id: number;
  };
};
export type HexBinary = string;
export interface Config {
  contract_owner: Addr;
  admin_fee: number;
  code_hash: HexBinary;
  code_id: number;
  latest_infusion_id: number;
  max_bundles: number;
  max_infusions: number;
  max_per_bundle: number;
  min_creation_fee?: Coin | null;
  min_infusion_fee?: Coin | null;
  min_per_bundle: number;
}
export interface InfusionsResponse {
  infusions: InfusionState[];
}
export interface InfusionState {
  collections: NFTCollection[];
  infused_collection: InfusedCollection;
  infusion_params: InfusionParamState;
  payment_recipient: Addr;
}
export interface InfusionParamState {
  min_per_bundle: number;
  mint_fee?: Coin | null;
  params?: BurnParams | null;
}
export type Boolean = boolean;