/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.12.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { GenericTokenBalance } from '../token'
import { Timestamp } from './common'
import {
  CollectionInfoResponse,
  ContractInfoResponse,
  RoyaltyInfoResponse,
} from './Sg721Base'

export type Uint128 = string
export interface InstantiateMsg {
  contract_owner?: string | null
  owner_fee: number
  cw721_code_id: number
  max_bundles?: number | null
  max_infusions?: number | null
  max_per_bundle?: number | null
  min_creation_fee?: Coin | null
  min_infusion_fee?: Coin | null
  min_per_bundle?: number | null
}
export interface Coin {
  amount: Uint128
  denom: string
  decimal?: string,
}
export type ExecuteMsg =
  | {
    update_config: {}
  }
  | {
    create_infusion: {
      infusions: Infusion[]
    }
  }
  | {
    infuse: {
      bundle: Bundle[]
      id: number
    }
  }
  | {
    upate_infusion_base_uri: {
      id: number
      base_uri: String
    }
  }
  | {
    upate_infusion_eligible_collections: {
      id: number
      to_add: NFTCollection[]
      to_remove: NFTCollection[]
    }
  }
  | {
    upate_infusion_mint_fee: {
      id: number
      mint_fee?: Coin | null
    }
  }
export type Addr = string

/// extends default infusion type with data for tokens & nft collections
export type InfusionWithDetails = Omit<
  Infusion,
  'collections' | 'infusion_params'
> & {
  eligibleCollections: InfusionsEligibleCollection[]
  infusionParamsGeneric: InfusionParamsGeneric
}

export type InfusionsEligibleCollection = {
  addr: string
  collectionInfo: CollectionInfoResponse
  contractInfo: ContractInfoResponse
  max_req: number | null | undefined
  min_req: number
  payment_substitute: GenericTokenBalance | null | undefined
}

export interface Infusion {
  owner: string
  description: string | null
  collections: NFTCollection[]
  infused_collection: InfusedCollection
  infusion_params: InfusionParams
  payment_recipient?: Addr | null
}
export interface NFTCollection {
  addr: Addr
  min_req: number
  max_req?: number | null
  payment_substitute?: Coin | null
}
export interface InfusedCollection {
  addr?: string | null
  admin?: string | null
  name: string
  description: string
  base_uri: string
  image: string
  num_tokens: number
  sg: boolean
  symbol: string
  royalty_info?: RoyaltyInfoResponse | null
  start_trading_time?: Timestamp | null
  explicit_content?: boolean | null
  external_link?: string | null
}

export interface InfusionParams {
  bundle_type: BundleType
  mint_fee?: Coin | null
  params?: BurnParams | null
  wavs_enabled: boolean
}
export interface BurnParams {
  compatible_traits?: CompatibleTraits | null
}
export interface CompatibleTraits {
  a: string
  b: string
}
export interface Bundle {
  nfts: NFT[]
}
export interface NFT {
  addr: Addr
  token_id: number
}
export type QueryMsg =
  | {
    config: {}
  }
  | {
    infusion: {
      addr: Addr
      id: number
    }
  }
  | {
    infusion_by_id: {
      id: number
    }
  }
  | {
    infusions: {
      addr: Addr
      index: number
    }
  }
export type HexBinary = string

/// extends default infusion type with data for tokens & nft collections
export type InfusionConfig = Omit<
  Config,
  'min_creation_fee' | 'max_creation_fee'
> & {
  creation_fee?: GenericTokenBalance | null
  infusion_fee?: GenericTokenBalance | null
}

export interface Config {
  contract_owner: Addr
  admin_fee: number
  code_hash: HexBinary
  code_id: number
  latest_infusion_id: number
  max_bundles: number
  max_infusions: number
  max_per_bundle: number
  min_creation_fee?: Coin | null
  min_infusion_fee?: Coin | null
  min_per_bundle: number
}
export interface InfusionsResponse {
  infusions: InfusionState[]
}
export interface InfusionState {
  collections: NFTCollection[]
  infused_collection: InfusedCollection
  infusion_params: InfusionParamState
  payment_recipient: Addr
}
/// extends default infusion type with data for tokens & nft collections
export type InfusionParamsGeneric = Omit<InfusionParamState, 'mint_fee'> & {
  mintFeeGeneric: GenericTokenBalance | null
}

export interface InfusionParamState {
  bundle_type: BundleType
  mint_fee?: Coin | null
  params?: BurnParams | null
}
export type Boolean = boolean

export type BlendNFTs = {
  addr: Addr
  min_req: number
  payment_substitute: boolean
}

export type BundleBlend = {
  blend_nfts: BlendNFTs[]
}

export type BundleType =
  | { all_of: Record<string, unknown> }
  | { any_of: { addrs: Addr[] } }
  | { any_of_blend: { blends: BundleBlend[] } }
