/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.12.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { selectorFamily } from 'recoil'

import { WithChainId } from '@dao-dao/types'
import {
  Boolean,
  Config,
  Infusion,
  InfusionsResponse,
} from '@dao-dao/types/contracts/CwInfuser'

import { CwInfuserQueryClient } from '../../../contracts'
import { signingCosmWasmClientAtom } from '../../atoms'

type QueryClientParams = WithChainId<{
  contractAddress: string
  sender: string
}>
export const queryClient = selectorFamily<
  CwInfuserQueryClient,
  QueryClientParams
>({
  key: 'cwInfuserQueryClient',
  get:
    ({ chainId, contractAddress }) =>
    ({ get }) => {
      const client = get(signingCosmWasmClientAtom({ chainId }))

      if (!client) {
        throw new Error(`SigningCosmWasmClient not found for chain ${chainId}`)
      }

      return new CwInfuserQueryClient(client, contractAddress)
    },
})
export const configSelector = selectorFamily<
  Config,
  QueryClientParams & {
    params: Parameters<CwInfuserQueryClient['config']>
  }
>({
  key: 'cwInfuserConfig',
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams))
      return await client.config(...params)
    },
})
export const infusionSelector = selectorFamily<
  Infusion,
  QueryClientParams & {
    params: Parameters<CwInfuserQueryClient['infusion']>
  }
>({
  key: 'cwInfuserInfusion',
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams))
      return await client.infusion(...params)
    },
})
export const infusionByIdSelector = selectorFamily<
  Infusion,
  QueryClientParams & {
    params: Parameters<CwInfuserQueryClient['infusionById']>
  }
>({
  key: 'cwInfuserInfusionById',
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams))
      return await client.infusionById(...params)
    },
})
export const infusionsSelector = selectorFamily<
  InfusionsResponse,
  QueryClientParams & {
    params: Parameters<CwInfuserQueryClient['infusions']>
  }
>({
  key: 'cwInfuserInfusions',
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams))
      return await client.infusions(...params)
    },
})
export const isInBundleSelector = selectorFamily<
  Boolean,
  QueryClientParams & {
    params: Parameters<CwInfuserQueryClient['isInBundle']>
  }
>({
  key: 'cwInfuserIsInBundle',
  get:
    ({ params, ...queryClientParams }) =>
    async ({ get }) => {
      const client = get(queryClient(queryClientParams))
      return await client.isInBundle(...params)
    },
})
