/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { ExecuteMsg,  Timestamp, Uint64, EventSegmentAccessType, Uint128, Action, Expiration, EventSegments, GuestDetails, Coin, Member, QueryMsg, ArrayOfAvEventContract, AvEventContract, Addr, OwnershipForAddr } from '@dao-dao/types/contracts/CwAveFactory'
import { InstantiateMsg as CwAveInitMsg } from '@dao-dao/types/contracts/CwAve'
export interface CwAveFactoryReadOnlyInterface {
  contractAddress: string;
  listAvEventContracts: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfAvEventContract>;
  listAvEventContractsReverse: ({
    limit,
    startBefore
  }: {
    limit?: number;
    startBefore?: string;
  }) => Promise<ArrayOfAvEventContract>;
  listAvEventContractsByInstantiator: ({
    instantiator,
    limit,
    startAfter
  }: {
    instantiator: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfAvEventContract>;
  listAvEventContractsByInstantiatorReverse: ({
    instantiator,
    limit,
    startBefore
  }: {
    instantiator: string;
    limit?: number;
    startBefore?: string;
  }) => Promise<ArrayOfAvEventContract>;
  ownership: () => Promise<OwnershipForAddr>;
  codeId: () => Promise<Uint64>;
}
export class CwAveFactoryQueryClient implements CwAveFactoryReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.listAvEventContracts = this.listAvEventContracts.bind(this);
    this.listAvEventContractsReverse = this.listAvEventContractsReverse.bind(this);
    this.listAvEventContractsByInstantiator = this.listAvEventContractsByInstantiator.bind(this);
    this.listAvEventContractsByInstantiatorReverse = this.listAvEventContractsByInstantiatorReverse.bind(this);
    this.ownership = this.ownership.bind(this);
    this.codeId = this.codeId.bind(this);
  }

  listAvEventContracts = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfAvEventContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_av_event_contracts: {
        limit,
        start_after: startAfter
      }
    });
  };
  listAvEventContractsReverse = async ({
    limit,
    startBefore
  }: {
    limit?: number;
    startBefore?: string;
  }): Promise<ArrayOfAvEventContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_av_event_contracts_reverse: {
        limit,
        start_before: startBefore
      }
    });
  };
  listAvEventContractsByInstantiator = async ({
    instantiator,
    limit,
    startAfter
  }: {
    instantiator: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfAvEventContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_av_event_contracts_by_instantiator: {
        instantiator,
        limit,
        start_after: startAfter
      }
    });
  };
  listAvEventContractsByInstantiatorReverse = async ({
    instantiator,
    limit,
    startBefore
  }: {
    instantiator: string;
    limit?: number;
    startBefore?: string;
  }): Promise<ArrayOfAvEventContract> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_av_event_contracts_by_instantiator_reverse: {
        instantiator,
        limit,
        start_before: startBefore
      }
    });
  };
  ownership = async (): Promise<OwnershipForAddr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownership: {}
    });
  };
  codeId = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      code_id: {}
    });
  };
}
export interface CwAveFactoryInterface extends CwAveFactoryReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createNativeAvEventContract: ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: CwAveInitMsg;
    label: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  updateCodeId: ({
    shitstrapCodeId
  }: {
    shitstrapCodeId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  updateOwnership: (action: Action, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
}
export class CwAveFactoryClient extends CwAveFactoryQueryClient implements CwAveFactoryInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createNativeAvEventContract = this.createNativeAvEventContract.bind(this);
    this.updateCodeId = this.updateCodeId.bind(this);
    this.updateOwnership = this.updateOwnership.bind(this);
  }

  createNativeAvEventContract = async ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: CwAveInitMsg;
    label: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_native_av_event_contract: {
        instantiate_msg: instantiateMsg,
        label
      }
    }, fee_, memo_, funds_);
  };
  updateCodeId = async ({
    shitstrapCodeId
  }: {
    shitstrapCodeId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_code_id: {
        shitstrap_code_id: shitstrapCodeId
      }
    }, fee_, memo_, funds_);
  };
  updateOwnership = async (action: Action, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_ownership: action
    }, fee_, memo_, funds_);
  };
}