/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Timestamp, Uint64, EventSegmentAccessType, Uint128, InstantiateMsg, EventSegments, GuestDetails, Coin, Member, ExecuteMsg, Binary, RegisteringGuest, CheckInDetails, QueryMsg, ArrayOfTicketPaymentOption, TicketPaymentOption, Addr, Config, ArrayOfEventSegments, Boolean, ArrayOfBoolean, ArrayOfGuestDetails } from '@dao-dao/types/contracts/CwAve'
export interface CwAveReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  eventSegments: () => Promise<ArrayOfEventSegments>;
  guestTypeDetails: ({
    guestType
  }: {
    guestType: string;
  }) => Promise<GuestDetails>;
  guestTypeDetailsAll: () => Promise<ArrayOfGuestDetails>;
  guestAttendanceStatus: ({
    eventStageId,
    guest
  }: {
    eventStageId: number;
    guest: string;
  }) => Promise<Boolean>;
  guestAttendanceStatusAll: ({
    guest
  }: {
    guest: string;
  }) => Promise<ArrayOfBoolean>;
  ticketPaymentOptionsByGuestType: ({
    guestType
  }: {
    guestType: string;
  }) => Promise<TicketPaymentOption>;
  allTicketPaymentOptions: () => Promise<ArrayOfTicketPaymentOption>;
}
export class CwAveQueryClient implements CwAveReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.eventSegments = this.eventSegments.bind(this);
    this.guestTypeDetails = this.guestTypeDetails.bind(this);
    this.guestTypeDetailsAll = this.guestTypeDetailsAll.bind(this);
    this.guestAttendanceStatus = this.guestAttendanceStatus.bind(this);
    this.guestAttendanceStatusAll = this.guestAttendanceStatusAll.bind(this);
    this.ticketPaymentOptionsByGuestType = this.ticketPaymentOptionsByGuestType.bind(this);
    this.allTicketPaymentOptions = this.allTicketPaymentOptions.bind(this);
    this
  }

  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  eventSegments = async (): Promise<ArrayOfEventSegments> => {
    return this.client.queryContractSmart(this.contractAddress, {
      event_segments: {}
    });
  };
  guestTypeDetails = async ({
    guestType
  }: {
    guestType: string;
  }): Promise<GuestDetails> => {
    return this.client.queryContractSmart(this.contractAddress, {
      guest_type_details: {
        guest_type: guestType
      }
    });
  };
  guestTypeDetailsAll = async (): Promise<ArrayOfGuestDetails> => {
    return this.client.queryContractSmart(this.contractAddress, {
      guest_type_details_all: {}
    });
  };
  guestAttendanceStatus = async ({
    eventStageId,
    guest
  }: {
    eventStageId: number;
    guest: string;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      guest_attendance_status: {
        event_stage_id: eventStageId,
        guest
      }
    });
  };
  guestAttendanceStatusAll = async ({
    guest
  }: {
    guest: string;
  }): Promise<ArrayOfBoolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      guest_attendance_status_a_l_l: {
        guest
      }
    });
  };
  ticketPaymentOptionsByGuestType = async ({
    guestType
  }: {
    guestType: string;
  }): Promise<TicketPaymentOption> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ticket_payment_options_by_guest_type: {
        guest_type: guestType
      }
    });
  };
  allTicketPaymentOptions = async (): Promise<ArrayOfTicketPaymentOption> => {
    return this.client.queryContractSmart(this.contractAddress, {
      all_ticket_payment_options: {}
    });
  };
}
export interface CwAveInterface extends CwAveReadOnlyInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  purchaseTickets: ({
    guests
  }: {
    guests: RegisteringGuest[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  checkInGuest: ({
    checkin,
    stage
  }: {
    checkin: CheckInDetails;
    stage: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
  refundUnconfirmedTickets: ({
    guests
  }: {
    guests: string[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
}
export class CwAveClient extends CwAveQueryClient implements CwAveInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.purchaseTickets = this.purchaseTickets.bind(this);
    this.checkInGuest = this.checkInGuest.bind(this);
    this.refundUnconfirmedTickets = this.refundUnconfirmedTickets.bind(this);
  }

  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee_, memo_, funds_);
  };
  purchaseTickets = async ({
    guests
  }: {
    guests: RegisteringGuest[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      purchase_tickets: {
        guests
      }
    }, fee_, memo_, funds_);
  };
  checkInGuest = async ({
    checkin,
    stage
  }: {
    checkin: CheckInDetails;
    stage: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      check_in_guest: {
        checkin,
        stage
      }
    }, fee_, memo_, funds_);
  };
  refundUnconfirmedTickets = async ({
    guests
  }: {
    guests: string[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      refund_unconfirmed_tickets: {
        guests
      }
    }, fee_, memo_, funds_);
  };
}