/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { StdFee } from "@cosmjs/amino";
import { Uint128, InstantiateMsg, Coin, ExecuteMsg, Addr, Infusion, NFTCollection, InfusedCollection, InfusionParams, BurnParams, CompatibleTraits, Bundle, NFT, QueryMsg, HexBinary, Config, InfusionsResponse, InfusionState, InfusionParamState, Boolean } from '@dao-dao/types/contracts/CwInfuser'
export interface CwInfuserReadOnlyInterface {
    contractAddress: string;
    config: () => Promise<Config>;
    infusion: ({
        addr,
        id
    }: {
        addr: Addr;
        id: number;
    }) => Promise<Infusion>;
    infusionById: ({
        id
    }: {
        id: number;
    }) => Promise<Infusion>;
    infusions: ({
        addr,
        index
    }: {
        addr: Addr;
        index: number;
    }) => Promise<InfusionsResponse>;
    isInBundle: ({
        collectionAddr,
        infusionId
    }: {
        collectionAddr: Addr;
        infusionId: number;
    }) => Promise<Boolean>;
}
export class CwInfuserQueryClient implements CwInfuserReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string) {
        this.client = client;
        this.contractAddress = contractAddress;
        this.config = this.config.bind(this);
        this.infusion = this.infusion.bind(this);
        this.infusionById = this.infusionById.bind(this);
        this.infusions = this.infusions.bind(this);
        this.isInBundle = this.isInBundle.bind(this);
    }
    config = async (): Promise<Config> => {
        return this.client.queryContractSmart(this.contractAddress, {
            config: {}
        });
    };
    infusion = async ({
        addr,
        id
    }: {
        addr: Addr;
        id: number;
    }): Promise<Infusion> => {
        return this.client.queryContractSmart(this.contractAddress, {
            infusion: {
                addr,
                id
            }
        });
    };
    infusionById = async ({
        id
    }: {
        id: number;
    }): Promise<Infusion> => {
        return this.client.queryContractSmart(this.contractAddress, {
            infusion_by_id: {
                id
            }
        });
    };
    infusions = async ({
        addr,
        index
    }: {
        addr: Addr;
        index: number;
    }): Promise<InfusionsResponse> => {
        return this.client.queryContractSmart(this.contractAddress, {
            infusions: {
                addr,
                index
            }
        });
    };
    isInBundle = async ({
        collectionAddr,
        infusionId
    }: {
        collectionAddr: Addr;
        infusionId: number;
    }): Promise<Boolean> => {
        return this.client.queryContractSmart(this.contractAddress, {
            is_in_bundle: {
                collection_addr: collectionAddr,
                infusion_id: infusionId
            }
        });
    };
}
export interface CwInfuserInterface extends CwInfuserReadOnlyInterface {
    contractAddress: string;
    sender: string;
    updateConfig: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
    createInfusion: ({
        collections
    }: {
        collections: Infusion[];
    }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
    infuse: ({
        bundle,
        infusionId
    }: {
        bundle: Bundle[];
        infusionId: number;
    }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<ExecuteResult>;
}
export class CwInfuserClient extends CwInfuserQueryClient implements CwInfuserInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
        super(client, contractAddress);
        this.client = client;
        this.sender = sender;
        this.contractAddress = contractAddress;
        this.updateConfig = this.updateConfig.bind(this);
        this.createInfusion = this.createInfusion.bind(this);
        this.infuse = this.infuse.bind(this);
    }
    updateConfig = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
        return await this.client.execute(this.sender, this.contractAddress, {
            update_config: {}
        }, fee_, memo_, funds_);
    };
    createInfusion = async ({
        collections
    }: {
        collections: Infusion[];
    }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
        return await this.client.execute(this.sender, this.contractAddress, {
            create_infusion: {
                collections
            }
        }, fee_, memo_, funds_);
    };
    infuse = async ({
        bundle,
        infusionId
    }: {
        bundle: Bundle[];
        infusionId: number;
    }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<ExecuteResult> => {
        return await this.client.execute(this.sender, this.contractAddress, {
            infuse: {
                bundle,
                infusion_id: infusionId
            }
        }, fee_, memo_, funds_);
    };
}