/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { QueryClient, UseQueryOptions, useQuery } from "@tanstack/react-query";
import { Timestamp, Uint64, EventSegmentAccessType, Uint128, InstantiateMsg, EventSegments, GuestDetails, Coin, Member, ExecuteMsg, Binary, RegisteringGuest, CheckInDetails, QueryMsg, TicketPaymentOption, Addr, Config, ArrayOfEventSegments, Boolean, ArrayOfBoolean, ArrayOfTicketPaymentOption, ArrayOfGuestDetails, ArrayOfGenericTokenGuestDetails } from '@dao-dao/types/contracts/CwAve'
import { CwAveQueryClient } from '../../../contracts/CwAve'
import { indexerQueries } from "../indexer";
import { getCosmWasmClientForChainId } from "@dao-dao/utils";
import { cw4GroupQueries } from "./Cw4Group";
import { AvEventInstance, GenericTokenBalance, TokenType } from "@dao-dao/types";
import { tokenQueries } from "../token";
export const cwAveQueryKeys = {
  contract: ([{
    contract: "cwAve"
  }] as const),
  address: (contractAddress: string) => ([{
    ...cwAveQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  eventInstance: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "event_instance",
    args
  }] as const),
  eventSegments: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "event_segments",
    args
  }] as const),
  guestTypeDetails: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "guest_type_details",
    args
  }] as const),
  guestTypeDetailsAll: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "guest_type_details_all",
    args
  }] as const),
  guestAttendanceStatus: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "guest_attendance_status",
    args
  }] as const),
  guestAttendanceStatusAll: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "guest_attendance_status_a_l_l",
    args
  }] as const),
  ticketPaymentOptionsByGuestType: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "ticket_payment_options_by_guest_type",
    args
  }] as const),
  allTicketPaymentOptions: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveQueryKeys.address(contractAddress)[0],
    method: "all_ticket_payment_options",
    args
  }] as const)
};

export const cwAveQueries = {
  config: <TData = Config>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: CwAveConfigQuery<TData>
  ): UseQueryOptions<Config, Error, TData> => ({
    queryKey: cwAveQueryKeys.config(contractAddress),
    queryFn: async () => {
      try {
        // Attempt indexer query first
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwave/config'
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveQueryClient(cosmWasmClient, contractAddress).config()
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  eventInstance: <TData = AvEventInstance>(
    queryClient: QueryClient,
    { chainId, contractAddress, connectedAddr, options }: CwAveEventInstanceQuery<TData>
  ): UseQueryOptions<AvEventInstance, Error, TData> => ({
    queryKey: cwAveQueryKeys.eventInstance(contractAddress),
    queryFn: async () => {
      // try {
      //   // Attempt indexer query first
      //   return await queryClient.fetchQuery(
      //     indexerQueries.queryContract({
      //       chainId,
      //       contractAddress,
      //       formula: 'cwave/eventInstance'
      //     })
      //   )
      // } catch (error) {
      // console.error('Indexer failed, falling back to contract query', error)
      const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
      const cwAveClient = new CwAveQueryClient(cosmWasmClient, contractAddress)
      const config = await cwAveClient.config()
      const eventSegments = await cwAveClient.eventSegments()
      const guestDetails = await cwAveClient.guestTypeDetailsAll()

      // get usher & guest info if wallet address is provided

      // query if we are admin
      const usherWeight = await queryClient.fetchQuery(cw4GroupQueries.member({
        chainId,
        contractAddress: config.event_usher_contract,
        args: {
          addr: connectedAddr
        }
      }))

      const guestWeight = !usherWeight.weight ? undefined : await queryClient.fetchQuery(cw4GroupQueries.member({
        chainId,
        contractAddress: config.event_guest_contract,
        args: {
          addr: connectedAddr
        }
      }))


      const guestDetailsGeneric: ArrayOfGenericTokenGuestDetails = await Promise.all(
        guestDetails.map(async (gd) => {
          // Process all ticket_costs in parallel
          const updatedTicketCosts = await Promise.all(
            gd.ticket_cost.map(async (tc) => {
              const token = await queryClient.fetchQuery(
                tokenQueries.info({
                  chainId,
                  type: TokenType.Native,
                  denomOrAddress: tc.denom,
                })
              );
              return {
                token: token,
                balance: tc.amount.toString()
              } as GenericTokenBalance;
            })
          );

          // Return updated guest detail with replaced ticket_costs
          return {
            ...gd,
            ticket_cost: updatedTicketCosts,
          };
        })
      );

      return {
        loading: false,
        eventChainId: chainId,
        eventContract: contractAddress,
        config: config,
        usherWeight,
        guestWeight,
        eventTimeline: eventSegments,
        eventGuestDetails: guestDetailsGeneric,
        completed: false,
      }
      // }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  eventSegments: <TData = ArrayOfEventSegments>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: CwAveEventSegmentsQuery<TData>
  ): UseQueryOptions<ArrayOfEventSegments, Error, TData> => ({
    queryKey: cwAveQueryKeys.eventSegments(contractAddress),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwave/eventSegments'
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveQueryClient(cosmWasmClient, contractAddress).eventSegments()
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  guestTypeDetails: <TData = GuestDetails>(
    queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwAveGuestTypeDetailsQuery<TData>
  ): UseQueryOptions<GuestDetails, Error, TData> => ({
    queryKey: cwAveQueryKeys.guestTypeDetails(contractAddress, options),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwave/guestTypeDetails',
            args,
          })
        );
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error);
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId);
        return new CwAveQueryClient(cosmWasmClient, contractAddress).guestTypeDetails({ guestType: args.guestType });
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  guestTypeDetailsAll: <TData = ArrayOfGuestDetails>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: CwAveGuestTypeDetailsAllQuery<TData>
  ): UseQueryOptions<ArrayOfGuestDetails, Error, TData> => ({
    queryKey: cwAveQueryKeys.guestTypeDetailsAll(contractAddress),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwave/guestTypeDetailsAll'
          })
        );
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error);
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId);
        return new CwAveQueryClient(cosmWasmClient, contractAddress).guestTypeDetailsAll();
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),
  guestAttendanceStatus: <TData = Boolean>(
    queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwAveGuestAttendanceStatusQuery<TData>
  ): UseQueryOptions<Boolean, Error, TData> => ({
    queryKey: cwAveQueryKeys.guestAttendanceStatus(contractAddress, args),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwave/guestAttendanceStatus',
            args: {
              eventStageId: args.eventStageId,
              guest: args.guest
            }
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveQueryClient(cosmWasmClient, contractAddress).guestAttendanceStatus({
          eventStageId: args.eventStageId,
          guest: args.guest
        })
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  guestAttendanceStatusAll: <TData = ArrayOfBoolean>(
    queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwAveGuestAttendanceStatusAllQuery<TData>
  ): UseQueryOptions<ArrayOfBoolean, Error, TData> => ({
    queryKey: cwAveQueryKeys.guestAttendanceStatusAll(contractAddress, args),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwave/guestAttendanceStatusAll',
            args: { guest: args.guest }
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveQueryClient(cosmWasmClient, contractAddress).guestAttendanceStatusAll({
          guest: args.guest
        })
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  ticketPaymentOptionsByGuestType: <TData = TicketPaymentOption>(
    queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwAveTicketPaymentOptionsByGuestTypeQuery<TData>
  ): UseQueryOptions<TicketPaymentOption, Error, TData> => ({
    queryKey: cwAveQueryKeys.ticketPaymentOptionsByGuestType(contractAddress, args),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwave/ticketPaymentOptionsByGuestType',
            args: { guestType: args.guestType }
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveQueryClient(cosmWasmClient, contractAddress).ticketPaymentOptionsByGuestType({
          guestType: args.guestType
        })
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  allTicketPaymentOptions: <TData = ArrayOfTicketPaymentOption>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: CwAveAllTicketPaymentOptionsQuery<TData>
  ): UseQueryOptions<ArrayOfTicketPaymentOption, Error, TData> => ({
    queryKey: cwAveQueryKeys.allTicketPaymentOptions(contractAddress),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwave/allTicketPaymentOptions'
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveQueryClient(cosmWasmClient, contractAddress).allTicketPaymentOptions()
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  })
};

export interface CwAveReactQuery<TResponse, TData = TResponse> {
  chainId: string
  contractAddress: string
  connectedAddr: string
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;

  };
}
export interface CwAveAllTicketPaymentOptionsQuery<TData> extends CwAveReactQuery<ArrayOfTicketPaymentOption, TData> { }
export interface CwAveTicketPaymentOptionsByGuestTypeQuery<TData> extends CwAveReactQuery<TicketPaymentOption, TData> {
  args: {
    guestType: string;
  };
}

export interface CwAveGuestAttendanceStatusAllQuery<TData> extends CwAveReactQuery<ArrayOfBoolean, TData> {
  args: {
    guest: string;
  };
}

export interface CwAveGuestAttendanceStatusQuery<TData> extends CwAveReactQuery<Boolean, TData> {
  args: {
    eventStageId: number;
    guest: string;
  };
}

export interface CwAveEventSegmentsQuery<TData> extends CwAveReactQuery<ArrayOfEventSegments, TData> { }
export interface CwAveConfigQuery<TData> extends CwAveReactQuery<Config, TData> { }
export interface CwAveEventInstanceQuery<TData> extends CwAveReactQuery<AvEventInstance, TData> { }
export interface CwAveGuestTypeDetailsAllQuery<TData> extends CwAveReactQuery<ArrayOfGuestDetails, TData> { }
export interface CwAveGuestTypeDetailsQuery<TData> extends CwAveReactQuery<GuestDetails, TData> {
  args: {
    guestType: string;
  };
}