/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { QueryClient, UseQueryOptions, useQuery } from "@tanstack/react-query";
import { ExecuteMsg, Timestamp, Uint64, EventSegmentAccessType, Uint128, Action, Expiration, EventSegments, GuestDetails, Coin, Member, QueryMsg, ArrayOfAvEventContract, AvEventContract, Addr, OwnershipForAddr } from '@dao-dao/types/contracts/CwAveFactory'
import { CwAveFactoryQueryClient } from '../../../contracts/CwAveFactory'
import { indexerQueries } from "../indexer";
import { getCosmWasmClientForChainId } from "@dao-dao/utils";
export const cwAveFactoryQueryKeys = {
  contract: ([{
    contract: "cwAveFactory"
  }] as const),
  address: (contractAddress: string) => ([{
    ...cwAveFactoryQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  listAvEventContracts: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveFactoryQueryKeys.address(contractAddress)[0],
    method: "list_av_event_contracts",
    args
  }] as const),
  listAvEventContractsReverse: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveFactoryQueryKeys.address(contractAddress)[0],
    method: "list_av_event_contracts_reverse",
    args
  }] as const),
  listAvEventContractsByInstantiator: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveFactoryQueryKeys.address(contractAddress)[0],
    method: "list_av_event_contracts_by_instantiator",
    args
  }] as const),
  listAvEventContractsByInstantiatorReverse: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveFactoryQueryKeys.address(contractAddress)[0],
    method: "list_av_event_contracts_by_instantiator_reverse",
    args
  }] as const),
  ownership: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveFactoryQueryKeys.address(contractAddress)[0],
    method: "ownership",
    args
  }] as const),
  codeId: (contractAddress: string, args?: Record<string, unknown>) => ([{
    ...cwAveFactoryQueryKeys.address(contractAddress)[0],
    method: "code_id",
    args
  }] as const)
};
export const cwAveFactoryQueries = {
  listAvEventContracts: <TData = ArrayOfAvEventContract>(
    // queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwAveFactoryListAvEventContractsQuery<TData>
  ): UseQueryOptions<ArrayOfAvEventContract, Error, TData> => ({
    queryKey: cwAveFactoryQueryKeys.listAvEventContracts(contractAddress, args),
    queryFn: async () => {
      // try {
      //   return await queryClient.fetchQuery(
      //     indexerQueries.queryContract({
      //       chainId,
      //       contractAddress,
      //       formula: 'cwaveFactory/listAvEventContracts',
      //       args: {
      //         limit: args.limit,
      //         startAfter: args.startAfter
      //       }
      //     })
      //   )
      // } catch (error) {
      //   console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveFactoryQueryClient(cosmWasmClient, contractAddress).listAvEventContracts({
          limit: args.limit,
          startAfter: args.startAfter
        })
      // }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  listAvEventContractsReverse: <TData = ArrayOfAvEventContract>(
    queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwAveFactoryListAvEventContractsReverseQuery<TData>
  ): UseQueryOptions<ArrayOfAvEventContract, Error, TData> => ({
    queryKey: cwAveFactoryQueryKeys.listAvEventContractsReverse(contractAddress, args),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwaveFactory/listAvEventContractsReverse',
            args: {
              limit: args.limit,
              startBefore: args.startBefore
            }
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveFactoryQueryClient(cosmWasmClient, contractAddress).listAvEventContractsReverse({
          limit: args.limit,
          startBefore: args.startBefore
        })
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  listAvEventContractsByInstantiator: <TData = ArrayOfAvEventContract>(
    queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwAveFactoryListAvEventContractsByInstantiatorQuery<TData>
  ): UseQueryOptions<ArrayOfAvEventContract, Error, TData> => ({
    queryKey: cwAveFactoryQueryKeys.listAvEventContractsByInstantiator(contractAddress, args),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwaveFactory/listAvEventContractsByInstantiator',
            args: {
              instantiator: args.instantiator,
              limit: args.limit,
              startAfter: args.startAfter
            }
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveFactoryQueryClient(cosmWasmClient, contractAddress).listAvEventContractsByInstantiator({
          instantiator: args.instantiator,
          limit: args.limit,
          startAfter: args.startAfter
        })
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  listAvEventContractsByInstantiatorReverse: <TData = ArrayOfAvEventContract>(
    queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwAveFactoryListAvEventContractsByInstantiatorReverseQuery<TData>
  ): UseQueryOptions<ArrayOfAvEventContract, Error, TData> => ({
    queryKey: cwAveFactoryQueryKeys.listAvEventContractsByInstantiatorReverse(contractAddress, args),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwaveFactory/listAvEventContractsByInstantiatorReverse',
            args: {
              instantiator: args.instantiator,
              limit: args.limit,
              startBefore: args.startBefore
            }
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveFactoryQueryClient(cosmWasmClient, contractAddress).listAvEventContractsByInstantiatorReverse({
          instantiator: args.instantiator,
          limit: args.limit,
          startBefore: args.startBefore
        })
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  ownership: <TData = OwnershipForAddr>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: CwAveFactoryOwnershipQuery<TData>
  ): UseQueryOptions<OwnershipForAddr, Error, TData> => ({
    queryKey: cwAveFactoryQueryKeys.ownership(contractAddress),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwaveFactory/ownership'
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveFactoryQueryClient(cosmWasmClient, contractAddress).ownership()
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  }),

  codeId: <TData = Uint64>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: CwAveFactoryCodeIdQuery<TData>
  ): UseQueryOptions<Uint64, Error, TData> => ({
    queryKey: cwAveFactoryQueryKeys.codeId(contractAddress),
    queryFn: async () => {
      try {
        return await queryClient.fetchQuery(
          indexerQueries.queryContract({
            chainId,
            contractAddress,
            formula: 'cwaveFactory/codeId'
          })
        )
      } catch (error) {
        console.error('Indexer failed, falling back to contract query', error)
        const cosmWasmClient = await getCosmWasmClientForChainId(chainId)
        return new CwAveFactoryQueryClient(cosmWasmClient, contractAddress).codeId()
      }
    },
    ...options,
    enabled: !!contractAddress && (options?.enabled !== undefined ? options.enabled : true)
  })
};
export interface CwAveFactoryReactQuery<TResponse, TData = TResponse> {
  chainId: string
  contractAddress: string
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface CwAveFactoryCodeIdQuery<TData> extends CwAveFactoryReactQuery<Uint64, TData> { }

export interface CwAveFactoryOwnershipQuery<TData> extends CwAveFactoryReactQuery<OwnershipForAddr, TData> { }

export interface CwAveFactoryListAvEventContractsByInstantiatorReverseQuery<TData> extends CwAveFactoryReactQuery<ArrayOfAvEventContract, TData> {
  args: {
    instantiator: string;
    limit?: number;
    startBefore?: string;
  };
}

export interface CwAveFactoryListAvEventContractsByInstantiatorQuery<TData> extends CwAveFactoryReactQuery<ArrayOfAvEventContract, TData> {
  args: {
    instantiator: string;
    limit?: number;
    startAfter?: string;
  };
}

export interface CwAveFactoryListAvEventContractsReverseQuery<TData> extends CwAveFactoryReactQuery<ArrayOfAvEventContract, TData> {
  args: {
    limit?: number;
    startBefore?: string;
  };
}

export interface CwAveFactoryListAvEventContractsQuery<TData> extends CwAveFactoryReactQuery<ArrayOfAvEventContract, TData> {
  args: {
    limit?: number;
    startAfter?: string;
  };
}
