/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.12.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import { QueryClient, UseQueryOptions } from '@tanstack/react-query'

import {
  Addr,
  Boolean,
  Config,
  Infusion,
  InfusionsResponse,
} from '@dao-dao/types/contracts/CwInfuser'
import { getCosmWasmClientForChainId } from '@dao-dao/utils'

import { CwInfuserQueryClient } from '../../../contracts/CwInfuser'

export const cwInfuserQueryKeys = {
  contract: [
    {
      contract: 'cwInfuser',
    },
  ] as const,
  address: (contractAddress: string | undefined) =>
    [
      {
        ...cwInfuserQueryKeys.contract[0],
        address: contractAddress,
      },
    ] as const,
  config: (
    contractAddress: string | undefined,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...cwInfuserQueryKeys.address(contractAddress)[0],
        method: 'config',
        args,
      },
    ] as const,
  infusion: (
    contractAddress: string | undefined,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...cwInfuserQueryKeys.address(contractAddress)[0],
        method: 'infusion',
        args,
      },
    ] as const,
  infusionById: (
    contractAddress: string | undefined,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...cwInfuserQueryKeys.address(contractAddress)[0],
        method: 'infusion_by_id',
        args,
      },
    ] as const,
  infusions: (
    contractAddress: string | undefined,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...cwInfuserQueryKeys.address(contractAddress)[0],
        method: 'infusions',
        args,
      },
    ] as const,
  isInBundle: (
    contractAddress: string | undefined,
    args?: Record<string, unknown>
  ) =>
    [
      {
        ...cwInfuserQueryKeys.address(contractAddress)[0],
        method: 'is_in_bundle',
        args,
      },
    ] as const,
}
export const cwInfuserQueries = {
  config: <TData = Config>(
    queryClient: QueryClient,
    { chainId, contractAddress, options }: CwInfuserConfigQuery<TData>
  ): UseQueryOptions<Config, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.config(contractAddress),
    queryFn: async () => {
      // try {
      //     // Attempt to fetch data from the indexer.
      //     return await queryClient.fetchQuery(
      //         indexerQueries.queryContract(queryClient, {
      //             chainId,
      //             contractAddress,
      //             formula: 'cwShitstrapFactory/listShitstrapContracts',
      //             args,
      //         })
      //     )
      // } catch (error) {
      //     console.error(error)
      // }

      // If indexer query fails, fallback to contract query.
      return new CwInfuserQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).config()
    },
    ...options,
    enabled:
      !!contractAddress &&
      (options?.enabled !== undefined ? options.enabled : true),
  }),
  infusion: <TData = Infusion>(
    queryClient: QueryClient,
    { chainId, contractAddress, args, options }: CwInfuserInfusionQuery<TData>
  ): UseQueryOptions<Infusion, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.infusion(contractAddress, args),
    queryFn: async () => {
      // try {
      //     // Attempt to fetch data from the indexer.
      //     return await queryClient.fetchQuery(
      //         indexerQueries.queryContract(queryClient, {
      //             chainId,
      //             contractAddress,
      //             formula: 'cwShitstrapFactory/listShitstrapContracts',
      //             args,
      //         })
      //     )
      // } catch (error) {
      //     console.error(error)
      // }

      // If indexer query fails, fallback to contract query.
      return new CwInfuserQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).infusion({
        id: args.id,
        addr: args.addr,
      })
    },
    ...options,
    enabled:
      !!contractAddress &&
      (options?.enabled !== undefined ? options.enabled : true),
  }),

  infusionById: <TData = Infusion>(
    queryClient: QueryClient,
    {
      chainId,
      contractAddress,
      args,
      options,
    }: CwInfuserInfusionByIdQuery<TData>
  ): UseQueryOptions<Infusion, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.infusionById(contractAddress, args),
    queryFn: async () => {
      // try {
      //     // Attempt to fetch data from the indexer.
      //     return await queryClient.fetchQuery(
      //         indexerQueries.queryContract(queryClient, {
      //             chainId,
      //             contractAddress,
      //             formula: 'cwShitstrapFactory/listShitstrapContracts',
      //             args,
      //         })
      //     )
      // } catch (error) {
      //     console.error(error)
      // }

      // If indexer query fails, fallback to contract query.
      return new CwInfuserQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).infusionById({
        id: args.id,
      })
    },
    ...options,
    enabled:
      !!contractAddress &&
      (options?.enabled !== undefined ? options.enabled : true),
  }),
  infusions: <TData = InfusionsResponse>(
    queryClient: QueryClient,
    { contractAddress, chainId, args, options }: CwInfuserInfusionsQuery<TData>
  ): UseQueryOptions<InfusionsResponse, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.infusions(contractAddress, args),
    queryFn: async () => {
      // try {
      //     // Attempt to fetch data from the indexer.
      //     return await queryClient.fetchQuery(
      //         indexerQueries.queryContract(queryClient, {
      //             chainId,
      //             contractAddress,
      //             formula: 'cwShitstrapFactory/listShitstrapContracts',
      //             args,
      //         })
      //     )
      // } catch (error) {
      //     console.error(error)
      // }

      // If indexer query fails, fallback to contract query.
      return new CwInfuserQueryClient(
        await getCosmWasmClientForChainId(chainId),
        contractAddress
      ).infusions({
        addr: args.addr,
        index: args.index,
      })
    },
    ...options,
    enabled:
      !!contractAddress &&
      (options?.enabled !== undefined ? options.enabled : true),
  }),
  // isInBundle: <TData = Boolean>(
  //   queryClient: QueryClient,
  //   { chainId, contractAddress, args, options }: CwInfuserIsInBundleQuery<TData>
  // ): UseQueryOptions<Boolean, Error, TData> => ({
  //   queryKey: cwInfuserQueryKeys.isInBundle(contractAddress, args),
  //   queryFn: async () => {
  //     // try {
  //     // Attempt to fetch data from the indexer.
  //     return await queryClient.fetchQuery(
  //         indexerQueries.queryContract(queryClient, {
  //             chainId,
  //             contractAddress,
  //             formula: 'cwShitstrapFactory/listShitstrapContracts',
  //             args,
  //         })
  //     )
  // } catch (error) {
  //     console.error(error)
  // }

  // If indexer query fails, fallback to contract query.
  // return new CwInfuserQueryClient(
  //   await getCosmWasmClientForChainId(chainId),
  //   contractAddress
  // ).isInBundle({
  //   collectionAddr: args.collectionAddr,
  //   infusionId: args.infusionId,
  // })
  // },
  //   ...options,
  //   enabled:
  //     !!contractAddress &&
  //     (options?.enabled !== undefined ? options.enabled : true),
  // }),
}
export interface CwInfuserReactQuery<TResponse, TData = TResponse> {
  chainId: string
  contractAddress: string
  options?: Omit<
    UseQueryOptions<TResponse, Error, TData>,
    "'queryKey' | 'queryFn' | 'initialData'"
  > & {
    initialData?: undefined
  }
}
export interface CwInfuserIsInBundleQuery<TData>
  extends CwInfuserReactQuery<Boolean, TData> {
  args: {
    collectionAddr: Addr
    infusionId: number
  }
}
export interface CwInfuserInfusionsQuery<TData>
  extends CwInfuserReactQuery<InfusionsResponse, TData> {
  args: {
    addr: Addr
    index: number
  }
}
export interface CwInfuserInfusionByIdQuery<TData>
  extends CwInfuserReactQuery<Infusion, TData> {
  args: {
    id: number
  }
}
export interface CwInfuserInfusionQuery<TData>
  extends CwInfuserReactQuery<Infusion, TData> {
  args: {
    addr: Addr
    id: number
  }
}
export interface CwInfuserConfigQuery<TData>
  extends CwInfuserReactQuery<Config, TData> { }
